server:
    port: 4500
# 数据源
spring:
    application:
        name: las-backend-project-managerial-audits-4500
    cloud:
        nacos:
            config:
                server-addr: 127.0.0.1:8848
    servlet:
        # 文件上传限制
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    cache:
        type: redis
    redis:
        host: r-uf6eakqa522i0nzojzpd.redis.rds.aliyuncs.com
        port: 6379
        database: 0
        username: main
        password: LazyAlienServer2024!
        timeout: 3000ms
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                max-wait: 3000ms
                min-idle: 20

# log4j2
logging:
    level:
        cn.jay.repository: trace