server:
  port: 9000

spring:
  application:
    name: las-backend-api-gateway-9000
  cloud:
    #GateWay
    gateway:
      # 全局的跨域处理
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000  # 这次跨域检测的有效期
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
      routes:
        #用户模块route
        - id: user
          uri: http://localhost:3000
          predicates:
            - Path=/usersignin/**
            - Method=GET,POST
        #项目管理-提交
        - id: project-managerial-submit
          uri: http://localhost:4000
          predicates:
              - Path=/project-managerial-submit/**
              - Method=GET,POST
        #项目管理-审核
        - id: project-managerial-audits
          uri: http://localhost:4500
          predicates:
              - Path=/project-managerial-audits/**
              - Method=GET,POST
        #公告
        - id: las-backend-bulletin-5000
          uri: http://localhost:5000
          predicates:
            - Path=/bulletin/**
            - Method=GET,POST
    nacos:
      config:
        server-addr: 127.0.0.1:8848
