server:
    port: 4000
# 数据源
spring:
    application:
        name: las-backend-project-managerial-submit-4000
    cloud:
        nacos:
            config:
                server-addr: 127.0.0.1:8848
    servlet:
        # 文件上传限制
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    data:
        # mongodb
        mongodb:
            uri: mongodb://127.0.0.1:27017/projectManagerial
    cache:
        type: redis
    redis:
        host: 127.0.0.1
        timeout: 3000ms
        port: 6379
        database: 0
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                max-wait: 3000ms
                min-idle: 20

# log4j2
logging:
    level:
        cn.jay.repository: trace